name: Build

on:
  push:
    branches: [ "main" , "develop"]

  pull_request:
    branches: [ "main" , "develop"]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        changelog: ${{ steps.tag_version.outputs.changelog }}
    steps:
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUBTOKEN }}
        
  build:
    runs-on: ubuntu-latest
    needs: version
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Test
      run: go test -v ./...
      
    - name: Build
      uses: thatisuday/go-cross-build@v1
      with:
            platforms: 'linux/386, linux/amd64, linux/arm ,windows/386, windows/amd64, windows/arm'
            name: 'semver-cli'
            dest: 'dist'
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
          name: dist
          path: |
            dist

  docker:

    runs-on: ubuntu-latest
    needs:  [version, build]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/jfwenisch/semver-cli:${{needs.version.outputs.tag}}
            ghcr.io/jfwenisch/semver-cli:latest
          labels: ${{ steps.meta.outputs.labels }}

  release:
    runs-on: ubuntu-latest
    needs:  [version, build, docker]
    steps:
    - uses: actions/checkout@v3

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      if: github.ref == 'refs/heads/main'
      with:
        tag: ${{needs.version.outputs.tag}}
        name: Release ${{needs.version.outputs.tag}}
        artifacts: "dist/semver-cli-*"
        body: ${{needs.version.outputs.changelog}}
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: dist
    
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      if: github.ref == 'refs/heads/develop'
      with:
        tag: ${{needs.version.outputs.tag}}
        name: Release ${{needs.version.outputs.tag}}
        artifacts: "dist/semver-cli-*"
        prerelease: true
        artifactErrorsFailBuild: true
        body: ${{needs.version.outputs.changelog}}
